---
- name: Install apt packages for nginx
  apt:
    pkg:
    - curl
    - gnupg2
    - ca-certificates
    - lsb-release
    update_cache: yes
  tags: nginx

- name: Apt repository
  apt_repository:
    repo: deb http://nginx.org/packages/ubuntu {{ ansible_distribution_release }} nginx
    state: present
    filename: nginx
    update_cache: no
  tags: nginx

- name: Import nginx_signing.key
  apt_key:
    url: https://nginx.org/keys/nginx_signing.key
    state: present
  tags: nginx

- name: Update cache
  apt:
    update_cache: yes
    force: yes
  tags: nginx

- name: Install nginx
  apt:
    pkg:
    - nginx
  tags: nginx

- name: Start nginx
  service:
    name: nginx
    state: started
    enabled: yes
  tags: nginx

- name: Allow all access to tcp port 80,443
  ufw:
    rule: allow
    port: '{{ item }}'
    proto: tcp
  loop:
    - '80'
    - '443'
  when: ansible_distribution == 'Ubuntu'
  tags: nginx

- name: Add nginx config on dest
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/conf.d/default.conf
    owner: root
    group: root
    mode: 0644
  notify: Restart_service_nginx
  tags: nginx

- name: Add maintanence.html on dest
  template:
    src: templates/under-maintanence.html.j2
    dest: /usr/share/nginx/html/under-maintanence.html
    owner: root
    group: root
    mode: 0644
  notify: Restart_service_nginx
  tags: nginx
