---
- name: Install apt packages for nginx
  apt:
    pkg:
    - curl
    - gnupg2
    - ca-certificates
    - lsb-release
    update_cache: yes
  when: ansible_distribution == 'Ubuntu'
  become: True
  tags:
    - install

- name: apt_repository
  apt_repository:
    repo: deb http://nginx.org/packages/ubuntu {{ ansible_distribution_release }} nginx
    state: present
    filename: nginx
    update_cache: no
  when: ansible_distribution == 'Ubuntu'
  become: True
  tags:
    - install

- name: import key
  apt_key:
    url: https://nginx.org/keys/nginx_signing.key
    state: present
  when: ansible_distribution == 'Ubuntu'
  become: True
  tags:
    - install

- name: update_cache
  apt:
    update_cache: yes
    force: yes
  become: True
  when: ansible_distribution == 'Ubuntu'
  tags:
    - install

- name: install nginx
  apt:
    pkg:
    - nginx
  when: ansible_distribution == 'Ubuntu'
  become: True
  tags:
    - install

- name: nginx start
  service:
    name: nginx
    state: started
    enabled: yes
  become: True
  tags:
    - install

- name: Allow all access to tcp port 80,443
  ufw:
    rule: allow
    port: '{{ item }}'
    proto: tcp
  loop:
    - '80'
    - '443'
  when: ansible_distribution == 'Ubuntu'
  become: true
  tags:
    - install

- name: add nginx config on dest
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/conf.d/default.conf
    owner: root
    group: root
    mode: 0644
  notify: Restart_service_nginx
  become: true
  tags:
    - install

- name: add maintanence.html on dest
  template:
    src: templates/under-maintanence.html.j2
    dest: /usr/share/nginx/html/under-maintanence.html
    owner: root
    group: root
    mode: 0644
  notify: Restart_service_nginx
  become: true
  tags:
    - install
