---
- name: Start_service_docker
  service: 
    name: docker
    state: started  
  become: True

- name: Enable_service_docker
  service: 
    name: docker
    enabled: yes
  become: true

- name: Restart_service_docker
  service:
    name: docker
    state: restarted
  become: true
