---
- name: Start_service_docker
  service: 
    name: docker
    state: started

- name: Enable_service_docker
  service: 
    name: docker
    enabled: yes

- name: Restart_service_docker
  service:
    name: docker
    state: restarted
