---
- name: Start_service_nginx
  service: 
    name: nginx
    state: started  
  become: True

- name: Enable_service_nginx
  service: 
    name: nginx
    enabled: yes
  become: true

- name: Restart_service_nginx
  service:
    name: nginx
    state: restarted
  become: true