---
- name: Start_service_nginx
  service:
    name: nginx
    state: started
  become: true

- name: Enable_service_nginx
  service:
    name: nginx
    enabled: true
  become: true

- name: Restart_service_nginx
  service:
    name: nginx
    state: restarted
  become: true
...
