---
- name: common | Set timezone to Europe/Moscow
  timezone:
    name: Europe/Moscow
  tags: common

- name: common | Add the user '{{ user }}' with a specific uid and a primary group of 'sudo'
  user:
    name: '{{ user }}'
    comment: '{{ user_comment }}'
    shell: /bin/bash
    password: '{{ user_password }}'
    group: sudo
  tags: common

- name: common | Add my authorized_key
  authorized_key:
    user: '{{ user }}'
    state: present
    key: https://github.com/nedago.keys
  tags: common

- name: common | Set authorized key taken from file
  authorized_key:
    user: nedago
    state: present
    key: "{{ lookup('file', 'id_rsa.pub') }}"
  tags: common

- name: common | Allow all access to tcp port 9921, 22
  ufw:
    rule: allow
    port: '{{ item }}'
    proto: tcp
  loop:
    - '9921'
    - '22'
  tags: common

- name: common | Enable UFW
  ufw:
    state: enabled
  tags: common

- name: common | Install packages
  apt:
    pkg:
    - htop
    - vim
    - ntp
    - unzip
    - git
    update_cache: yes
  tags: common

- name: common | Creates directory
  file:
    path: /var/www/site
    state: directory
    owner: www-data
    group: www-data
    mode: 0775
  tags: common


- name: common | Delete content & directory
  file:
    state: absent
    path: /opt/this_repo/
  tags: common

- name: common | clone a private repository https://github.com/nedago/ansible.git
  git:
    repo: "https://read_user:{{ read_token }}@github.com/nedago/ansible.git"
    dest: "/opt/this_repo"
    version: "{{ branch }}"
    recursive: no
    force: yes
  tags: common


