---
- name: Add the user '{{ user }}' with a specific uid and a primary group of 'sudo'
  user:
    name: '{{ user }}'
    comment: '{{ user_comment }}'
    shell: /bin/bash
    password: '{{ user_password }}'
    group: sudo
  tags: common

- name: Add my authorized_key
  authorized_key:
    user: '{{ user }}'
    state: present
    key: https://github.com/nedago.keys
  tags: common

- name: Allow all access to tcp port 9921, 22
  ufw:
    rule: allow
    port: '{{ item }}'
    proto: tcp
  loop:
    - '9921'
    - '22'
  become: true
  tags: common

- name: Enable UFW
  ufw:
    state: enabled

- name: Install packages
  apt:
    pkg:
    - htop
    - vim
    - ntp
    - unzip
    update_cache: yes
  tags: common

- name: Set timezone to Europe/Moscow
  timezone:
    name: Europe/Moscow
  tags: common