---
- name: Add the user '{{ user }}' with a specific uid and a primary group of 'sudo'
  user:
    name: '{{ user }}'
    comment: '{{ user_comment }}'
    shell: /bin/bash
    password: '{{ user_password }}'
    group: sudo

- name: Add my authorized_key
  authorized_key:
    user: '{{ user }}'
    state: present
    key: https://github.com/nedago.keys

- name: Allow all access to tcp port 9921, 22
  ufw:
    rule: allow
    port: '{{ item }}'
    proto: tcp
  loop:
    - '9921'
    - '22'
  when: ansible_distribution == 'Ubuntu'
  become: true
  tags:
    - install

- name: Enable UFW
  ufw:
    state: enabled
  when: ansible_distribution == 'Ubuntu'