---
- name: Task 1 | Set timezone to Europe/Moscow
  timezone:
    name: Europe/Moscow
  tags: common

- name: Task 2 | Add the user '{{ user }}' with a specific uid and a primary group of 'sudo'
  user:
    name: '{{ user }}'
    comment: '{{ user_comment }}'
    shell: /bin/bash
    password: "{{ user_password | password_hash('sha512') }}"
    groups:
      - sudo
  tags: common

- name: Task 3 | Add my authorized_key
  authorized_key:
    user: '{{ user }}'
    state: present
    key: https://github.com/nedago.keys
  tags: common

- name: Task 4 | Set authorized key taken from file
  authorized_key:
    user: nedago
    state: present
    key: "{{ lookup('file', 'id_rsa.pub') }}"
  tags: common

- name: Task 5 | Allow all access to tcp port 9921, 22
  ufw:
    rule: allow
    port: '{{ item }}'
    proto: tcp
  loop:
    - '9921'
    - '22'
  tags: common

- name: Task 6 | Enable UFW
  ufw:
    state: enabled
  tags: common

- name: Task 7 | Install packages
  apt:
    pkg:
      - htop
      - vim
      - ntp
      - unzip
      - git
      - net-tools
    update_cache: true
  tags: common

- name: Task 8 | Creates directory
  file:
    path: /var/www/site
    state: directory
    owner: www-data
    group: www-data
    mode: 0775
  tags: common

- name: Task 9 | Delete content & directory
  file:
    state: absent
    path: /opt/this_repo/
  tags: common

- name: Task 10 | Clone a private repository https://github.com/nedago/ansible.git
  git:
    repo: "https://read_user:{{ read_token }}@github.com/nedago/ansible.git"
    dest: "/opt/this_repo"
    version: "{{ branch }}"
    recursive: false
    force: true
  tags: common

- name: Task 11 | Set File Rights
  file:
    path: "/opt/this_repo/README.md"
    owner: 'root'
    group: 'root'
    mode: 0600
  tags: common
...
