---
- name: Task 1 | Install apt packages
  apt:
    pkg:
      - ca-certificates
      - curl
      - gnupg
    update_cache: true
  tags: docker

- name: Task 2 | Add Docker’s official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
  tags: docker

- name: Task 3 | Add repository docker
  apt_repository:
    repo: deb [arch=arm64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
  tags: docker

- name: Task 4 | Install docker pakages
  apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
      - docker-compose
      - python3-pip
    update_cache: true
  tags: docker

- name: Task 5 | Creates directory
  file:
    path: /etc/docker
    state: directory
  tags: docker

- name: Task 6 | Copy file daemon.json on dest
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0644
  notify: Restart_service_docker
  tags: docker

- name: Task 7 | Add the user '{{ host_user }}' group of 'docker'
  user:
    name: "{{ user }}"
    comment: "{{ user_comment }}"
    group: docker
  tags: docker

# - name: Task 8 | Install required python docker modules
#   pip:
#     name:
#         - docker == 7.0.0
#         - docker-compose == 1.29.2
#   tags: docker
...
