---
- name: docker | Install apt packages
  apt: 
    pkg: 
    - ca-certificates
    - curl
    - gnupg
    update_cache: yes
  tags: docker

- name: docker | Add Docker’s official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
  tags: docker

- name: docker | Add repository docker
  apt_repository:
    repo: deb [arch=arm64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
  tags: docker

- name: docker | Install docker pakages
  apt: 
    pkg: 
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin
    - python3-pip
    update_cache: yes
  tags: docker

- name: docker | Creates directory
  file:
    path: /etc/docker
    state: directory
  tags: docker

- name: docker | Copy file daemon.json on dest
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0644
  notify: Restart_service_docker
  tags: docker

- name: docker | Add the user '{{ host_user }}' group of 'docker'
  user:
    name: "{{ user }}"
    comment: "{{ user_comment }}"
    group: docker
  tags: docker

- name: docker | Install required python docker modules
  pip:
    name:
      - docker
      - docker-compose
  tags: docker