---
- name: Start_service_nginx
  service: 
    name: nginx
    state: started

- name: Enable_service_nginx
  service: 
    name: nginx
    enabled: yes

- name: Restart_service_nginx
  service:
    name: nginx
    state: restarted
...
